<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <OutputType>Library</OutputType>
    <RootNamespace>SmartVillage</RootNamespace>
    <AssemblyName>SmartVillage</AssemblyName>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
  <Reference Include="StardewModdingAPI">
    <HintPath>Libs/Smapi.Toolkit.dll</HintPath>
  </Reference>
  <Reference Include="GenericModConfigMenu">
    <HintPath>Libs/GenericModConfigMenu.dll</HintPath>
  </Reference>
  <Reference Include="Newtonsoft.Json">
    <HintPath>Libs/Newtonsoft.Json.dll</HintPath>
  </Reference>
</ItemGroup>

</Project>
